services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./bin/dev
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=production
      - BUNDLE_PATH=/usr/local/bundle
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

volumes:
  postgres_data:
